version: '2'
networks:
    app-tier:
        driver: bridge

services:
    authSvc:
        build: .
        container_name: "auth-svc"
        image: registry.avenueone.com/avo/auth-svc:01.00.00-SNAPSHOT
        ports:
        - 8950:8950
        links:
        - postgresdb
        depends_on:
        - postgresdb
        env_file:
        - ./auth-svc.env
        networks:
        - app-tier

    postgresdb:
        image: "postgres:10-alpine"
        restart: always
        ports:
        - 5432:5432
        volumes:
        - ./db/initialize.sql:/docker-entrypoint-initdb.d/init.sql
        environment:
            POSTGRES_PASSWORD: "auth1"
            POSTGRES_USER: "auth"
        networks:
        - app-tier
